# Addin play
# Install libwebp-tools
---
- name: "Add yarn repository."
  dnf:
    name: "https://extras.getpagespeed.com/release-el8-latest.rpm"
    state: present
- name: "Update repos cache and install libwebp-tools package."
  dnf:
    name: libwebp-tools
    state: present
    update_cache: yes
- name: "Remove libwebp-tools from siteinfo."
  include_role:
    name: apnscp/initialize-filesystem-template
    tasks_from: "remove-package.yml"
  vars:
    package: libwebp-tools
- name: "Install libwebp-tools package to siteinfo."
  include_role:
    name: apnscp/initialize-filesystem-template
    tasks_from: "install-package.yml"
  vars:
    package: libwebp-tools
    service: siteinfo
